<?php
/**
 * Asset enqueueing helper.
 *
 * @package StarterPlugin
 */

declare( strict_types=1 );

namespace StarterPlugin\Helpers;

defined( 'ABSPATH' ) || exit;

/**
 * Handles script and style registration from webpack build output.
 */
class Assets {

	/**
	 * Enqueue a script built by @wordpress/scripts.
	 *
	 * Reads the .asset.php sidecar file generated by the dependency-extraction
	 * plugin to get the correct version hash and WordPress dependencies.
	 *
	 * @param string $handle  Script handle (matches the webpack entry name).
	 * @param string $src_dir Relative path to the build directory from plugin root.
	 *
	 * @return void
	 */
	public static function enqueue_script( string $handle, string $src_dir = 'assets/build' ): void {
		$asset_file = STARTER_PLUGIN_DIR . $src_dir . '/' . $handle . '.asset.php';

		if ( ! file_exists( $asset_file ) ) {
			return;
		}

		$asset = require $asset_file;

		wp_enqueue_script(
			'starter-plugin-' . $handle,
			STARTER_PLUGIN_URL . $src_dir . '/' . $handle . '.js',
			$asset['dependencies'],
			$asset['version'],
			[
				'strategy'  => 'defer',
				'in_footer' => true,
			]
		);

		wp_set_script_translations(
			'starter-plugin-' . $handle,
			'starter-plugin',
			STARTER_PLUGIN_DIR . 'languages'
		);
	}

	/**
	 * Enqueue a style built by @wordpress/scripts.
	 *
	 * Uses the version hash from the .asset.php sidecar file for cache busting.
	 *
	 * @param string $handle  Style handle (matches the webpack entry name).
	 * @param string $src_dir Relative path to the build directory from plugin root.
	 *
	 * @return void
	 */
	public static function enqueue_style( string $handle, string $src_dir = 'assets/build' ): void {
		$asset_file = STARTER_PLUGIN_DIR . $src_dir . '/' . $handle . '.asset.php';

		if ( ! file_exists( $asset_file ) ) {
			return;
		}

		$asset = require $asset_file;

		wp_enqueue_style(
			'starter-plugin-' . $handle,
			STARTER_PLUGIN_URL . $src_dir . '/' . $handle . '.css',
			[],
			$asset['version']
		);
	}
}
